### ISSUE TITLE
Responsive Navigation

### ISSUE THREAD

**Issue by CristhianF7** [kubefirst/console#142]
## Problem

We want to refactor the navigation component, the current implementation was made to receive props but We'd prefer to use native CSS media queries rather than javascript screen listeners. 

## Acceptance Criteria

- Navigation should be responsive
- Adjust the version because is tied to the desktop version
- Use CSS media queries with `styled-media-query`
- Mobile first

## Implementation Example

Use `theme/media/index.ts` in the style component 

```typescript 
export const StyledComponent = styled.div`
  // mobile styles
  width: 614px;


  ${media.greaterThan('md')`
    // desktop styles
    width: 790px;
  `};
`;

```

### < 1028px

<img width="501" alt="Screenshot 2023-03-14 at 9 31 36 AM" src="https://user-images.githubusercontent.com/14883029/225035508-b8654479-f0da-4faa-bb7c-b106b23dbd80.png">

### > 1028px

<img width="1693" alt="Screenshot 2023-03-14 at 9 38 03 AM" src="https://user-images.githubusercontent.com/14883029/225035820-308a6c80-ec7b-4ebc-8bc0-c0bd828e1590.png">

**Comment by D-B-Hawk** [comment]
Hey @CristhianF7. I would love to take care of this issue for you. I will reach out for any questions i have.

**Comment by fharper** [comment]
@D-B-Hawk: that's awesome, thanks for contributing.

Feel free to ask any questions here, or on our [Slack community](https://kubefirst.io/slack) in **#helpind-hands** for anything kubefirst related or **#contributors** for specifics about this contribution (or contributing to kubefirst overall).
